#!/usr/bin/python3
import socket
import threading
import concurrent.futures
import argparse
import platform
from colorama import Fore

parser = argparse.ArgumentParser()
parser.add_argument("-a", "--address", help="ip address for scanning")
parser.add_argument("-f", "--full", help="Full scan argument is 0")
parser.add_argument("-s", "--speed", help="base scan argument is 0")


args = parser.parse_args()

print_lock = threading.Lock()
def scan(ip, port):
    scanner = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    scanner.settimeout(1)
    try:
        scanner.connect((ip, port))
        scanner.close()
        with print_lock:
            print(Fore.WHITE + f"[{port}]" + Fore.GREEN + " Opened")
    except:pass
ip = args.address
with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
    if args.full:
        for port in range(65535):
            executor.submit(scan, ip, port + 1)
    if args.speed:
        for port in range(1000):
            executor.submit(scan, ip, port + 1)
